version: '3'

services:
    postgres:
        image: "postgres:latest"
        container_name: postgres
        environment:
            POSTGRES_USER: nanoct
            POSTGRES_PASSWORD: 346873fgsdhjgfhjs7328trz782gdfjhsghj
            POSTGRES_DB: nanoct
        volumes:
            - pgdata:/var/lib/postgresql/data
            - ./pg_init.sql:/docker-entrypoint-initdb.d/init.sql
        networks:
            - nanoct_network

networks:
    nanoct_network:
        external: true

volumes:
    pgdata:
